//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoparkYonetimi.Models.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OtoparkYonetimiEntities : DbContext
    {
        public OtoparkYonetimiEntities()
            : base("name=OtoparkYonetimiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Araclar> Tbl_Araclar { get; set; }
        public virtual DbSet<Tbl_Kisiler> Tbl_Kisiler { get; set; }
        public virtual DbSet<Tbl_ParkYeri> Tbl_ParkYeri { get; set; }
        public virtual DbSet<Tbl_Kullanicilar> Tbl_Kullanicilar { get; set; }
    }
}
