//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoparkYonetimi.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ParkYeri
    {
        public int ParkYeriId { get; set; }
        public string ParkYeri { get; set; }
        public int AracId { get; set; }
        public Nullable<decimal> ParkUcreti { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual Tbl_Araclar Tbl_Araclar { get; set; }
    }
}
